apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: learn
  namespace: argocd
spec:
  # Project description
  description: Learn Project

  # Allow manifests to deploy from our Git repos
  sourceRepos:
    - 'git@github.com:henryhoen/greenfield-argo.git'
    - 'git@github.com:henryhoen/greenfield-cd.git'
    - 'git@github.com:henryhoen/greenfield.git'

  # Only permit applications to deploy to the greenfield namespace in the same cluster
  destinations:
    - namespace: greenfield
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  # Allow all cluster-scoped resources from being created
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
